### ISSUE TITLE
"Size too big: Data ends at 0x1e51e0, which is larger than the specified range."

### ISSUE THREAD

**Issue by KrazyGyro9704** [Fast-64/fast64#155]
So, I was trying to remove all of the Toad model's polygons so that it wouldn't appear in-game. I wanted the ROM to be compatible with other Super Mario 64 tools, so I set the Import/Export options to Binary. I was able to successfully import and edit the model, but once I go to export it, it gives me this error:
"Size too big: Data ends at 0x1e51e0, which is larger than the specified range."
What does this mean, and how do I fix it?

**Comment by Dragorn421** [comment]
Same as #99 , #163

> Binary mode is vaguely unsupported, like a legacy feature, not really maintained
>
> It'll probably never be fixed, it's more likely to be removed
