### ISSUE TITLE
Binary Exporting outputs an unplayable ROM of Super Mario 64

### ISSUE THREAD

**Issue by NARbluebear** [Fast-64/fast64#163]
Upon exporting a modified version of Mario's model to a new ROM of Super Mario 64, I learned quickly that I couldn't get into the game's intro cutscene. All sound works as intended, the code just seemingly freezes up when it has to load Mario's model. I could confirm the sound part by waiting until one of the demos played, and it was just a white screen with the title music playing. The game doesn't respond to my inputs after this. I got curious and tested it with just the default mario.blend file, and it still froze. I've confirmed that both the original and extended ROMs work just fine, so it must be a problem with the plugin. If needed, I can disclose where I got my ROM privately. I'm not a Python expert, so I can't describe exactly what's wrong, but if I had to guess, it has something to do with the export code. I have yet to try C exporting. I've followed the tutorial videos to a T, if that helps.
Extra info:
- Windows 10 Pro 21H2
- Blender v3.2.0
- Fast64 v2.0.0
- ROM Region/Version: USA v1.0

**Comment by Dragorn421** [comment]
So you used binary exporting?

**Comment by NARbluebear** [comment]
That is correct. Is there something wrong with it at the moment?

**Comment by Dragorn421** [comment]
Binary exporting isn't well looked after, it's basically an abandoned feature, so yeah it may be broken
Consider joining the discord https://discord.gg/JtU2dGa

**Comment by NARbluebear** [comment]
Alright then. Thanks for the clarification. I'll try to see if I can figure out how to get C exporting working.

**Comment by NARbluebear** [comment]
A little update: I was able to build and play the modified copy using C exporting instead, meaning it *is* an issue with Binary exporting.

**Comment by Dragorn421** [comment]
Same as #99

> Binary mode is vaguely unsupported, like a legacy feature, not really maintained
>
> It'll probably never be fixed, it's more likely to be removed

**Comment by GlitchyPSIX** [comment]
I checked the results of the generated hierarchy/geolayout by Fast64 and it seems there's an infinite loop going on with jumps in the hierarchy/geolayout. This makes the game crash on a white screen. This is likely what's causing the problem and I'll see if I can check what's going on in the coming days.

**Comment by GlitchyPSIX** [comment]
> I checked the results of the generated hierarchy/geolayout by Fast64 and it seems there's an infinite loop going on with jumps in the hierarchy/geolayout. This makes the game crash on a white screen. This is likely what's causing the problem and I'll see if I can check what's going on in the coming days.

From what I have managed to deduce so far, this is an issue with the v5 materials. Something about the way they jump back is messing up the branching order in Binary.
