### ISSUE TITLE
'Material' has no attribute 'rdp_settings'

### ISSUE THREAD

**Issue by KorbinCode** [Fast-64/fast64#170]
I keep getting this error when i try to export to C, and i have no idea why. please get back to me ASAP.

**Comment by Dragorn421** [comment]
<img src="https://starecat.com/content/wp-content/uploads/as-asap-as-possible.jpg" width="30%">

Please show the full error
(get on discord for faster communication)

**Comment by Dragorn421** [comment]
Closing (inactive and no details to reproduce), feel free to reopen if needed (also there is a fast64 Discord)
