### ISSUE TITLE
'Material' has no attribute 'rdp_settings'

### ISSUE THREAD

**Issue by stvene3004** [Fast-64/fast64#196]
Happens fer most .blend files that come with Fast64, specifically the Mario .blend, and the two Skinned Mario .blends, and also .blends that used the older 1.0 version. Ya export the armature geolayout and this happens.

![image](https://user-images.githubusercontent.com/54620586/205483772-06c9a354-5301-481b-b8af-65cc9c27a5c6.png)

**Comment by Yanis42** [comment]
can you give steps to reproduce that error? #170 mentioned that issue but it was closed since it was inactive and lacked informations

also you should consider joining the Discord server as it will be easier to talk and figure out what's wrong (link in readme)

**Comment by Yanis42** [comment]
(actually if it happens only with blends from the repo it not really concerning I guess)

**Comment by stvene3004** [comment]
I really do not have any frickin' idea why that happens at all. All I know is that if ya export geolayouts right now, the materials will just act up and not allow me t' export anything. If ya want to though, I can give ya one o' my .blends to inspect the problem. Otherwise, the only way t' reproduce this is t' just try it on one o' the Mario .blends or any .blends that may have used a version prior to 1.0.

**Comment by stvene3004** [comment]
> (actually if it happens only with blends from the repo it not really concerning I guess)

Actually most o' my files won't work anymore. They happen t' have the exact same error when I export 'em with Fast64 2.0, so now I really don't know what t' do.

**Comment by Agent-11** [comment]
Not exactly a bug, upgrade your materials properly and purge old materials and node groups and restart Blender when you do that

**Comment by stvene3004** [comment]
That didn't work. I also tried t' downgrade my Blender t' 3.2 three times with three versions. And it didn't work either. I dug a lil' deeper and saw that a part o' this error is due to the fact that Fast64 can't open this "f3d_material_library.blend" file. I do not know what t' do about this.

**Comment by Dragorn421** [comment]
I cannot reproduce this with latest fast64 ( 23827622352ec274ed882d0362fac9bce13ed2f6 ), with the blends in the repo.

Opening `mario.blend` and `LowPolySkinnedMario.blend` happens without errors, the "upgrade materials" popup shows fine, the upgrade goes fine, the result looks fine, no error anywhere

Same with `LowPolySkinnedMario_V5.blend` except no "upgrade materials" popup or upgrade needed

**Comment by stvene3004** [comment]
Well I heard they fixed 'em already so I might as well close this issue later.

**Comment by Dragorn421** [comment]
Can't reproduce / fixed ?
