### ISSUE TITLE
"Cannot unpack non-iterable FImageKey object"

### ISSUE THREAD

**Issue by KrazyGyro9704** [Fast-64/fast64#215]
I was trying to remesh Mario's geolayout, and when I exported it, I got this message. It doesn't tell me any information on it, either, not the object in question, not the image file, nothing. I even tried changing all of the texture materials and files to RGBA16, and that didn't fix the issue. What could be causing this?

**Comment by Dragorn421** [comment]
Hello, thanks for the report

I think this is known and fixed by the following pull request:

https://github.com/Fast-64/fast64/pull/213

You can try it out until it's reviewed and merged into main fast64 :) (soon tm hopefully)

**Comment by BeverlyBean** [comment]
save textures PR got merged so this issue is solved
