### ISSUE TITLE
How do i get "mario_skel.blend"?

### ISSUE THREAD

**Issue by SuperMarioYAHOOYAHOO** [Fast-64/fast64#225]
help

**Comment by Dragorn421** [comment]
Hi, can you provide more details about what you are looking for?

**Comment by SuperMarioYAHOOYAHOO** [comment]
> Hi, can you provide more details about what you are looking for?

basicly, on sm64-roblox, you can use python scripts to extract animations. i was told mario_skel.blend comes with fast64. i cannot find it.

**Comment by Dragorn421** [comment]
I don't know what that file could be

There are three blend files in the repo, all at the repo's root
Check them out maybe one of them is what you're looking for.

Otherwise can't really help any further
