### ISSUE TITLE
Groups of the bad vert that don't correspond to a bone: ['000-displaylist']

### ISSUE THREAD

**Issue by MarioTechGuy** [Fast-64/fast64#250]
All vertices must be part of a vertex group, be non-trivially weighted (> 0.4), and the vertex group must correspond to a bone in the armature.
Groups of the bad vert that don't correspond to a bone: ['000-displaylist']. If a vert is supposed to belong to this group then either a bone is missing or you have the wrong group.
Groups of the bad vert below weight limit: []. If a vert is supposed to belong to one of these groups then make sure to increase its weight.
I don't know what I am doing wrong I did everting correctly

**Comment by jesusyoshi54** [comment]
This isn't an issue you just have something wrong with your model.
ask for help from somebody in the discord
