### ISSUE TITLE
Too many connecting vertices in skinned triangles

### ISSUE THREAD

**Issue by MarioTechGuy** [Fast-64/fast64#260]
Too many connecting vertices in skinned triangles for bone '000-offset.001'. Max is 14 on parent bone, currently at 21. Note that a vertex with different UVs/normals/materials in connected faces will count more than once. Try keeping UVs contiguous, and avoid using split normals.
![Wonder96](https://github.com/Fast-64/fast64/assets/131635742/830eb1e6-b0e5-41ff-93d7-36c075be195b)

im making a mod called Wonder96 dynos pack for mario 64 but I get this issue everytime I export

**Comment by BeanieCoders** [comment]
I have the same issue
