### ISSUE TITLE
I Cant make a fast3d material. (python error and crash)

### ISSUE THREAD

**Issue by Mrmaxidepapel** [Fast-64/fast64#267]
Basically, when i click the create new material button in f3d, it just gives an error and sometimes crashes, I'm on version 3.6 of blender, I don't know if I should have an older one or something like that, here's the error that appears.

<img width="770" alt="Captura de pantalla 2023-12-14 104118" src="https://github.com/Fast-64/fast64/assets/143361819/dcd961d1-f0d1-4a32-91af-bd952ef22949">

**Comment by Yanis42** [comment]
I don't remember if the latest release of fast64 contains the 3.0 fix, try the latest version of the main branch and it should work properly (on 4.0 too)

**Comment by Mrmaxidepapel** [comment]
okay

**Comment by Dragorn421** [comment]
I assume updating fast64 fixed the issue.
