### ISSUE TITLE
[BLENDER 4.0] ERROR: Principled BSDF to F3D Converter

### ISSUE THREAD

**Issue by RayArmahedgehog** [Fast-64/fast64#301]
![image](https://github.com/Fast-64/fast64/assets/95722707/c5d1815d-a1c5-48ce-99be-242f5d325165)
I just press the button and this error shows up

**Comment by Dragorn421** [comment]
Hey :wave: 
This has been fixed recently (#296)
Update fast64 to latest main, cf instructions in the README: https://github.com/Fast-64/fast64#updater

**Comment by RayArmahedgehog** [comment]
I downloaded Fast64 yesterday

**Comment by Dragorn421** [comment]
If you downloaded it from the releases that would be the latest release only, it doesn't have the most recent changes. Use the updater, for real

**Comment by RayArmahedgehog** [comment]
![image](https://github.com/Fast-64/fast64/assets/95722707/5864f6a9-3960-4519-b416-a91d7b75104b)
![image](https://github.com/Fast-64/fast64/assets/95722707/192369c6-a065-49a8-ba1a-f0577e9a1aa5)
![image](https://github.com/Fast-64/fast64/assets/95722707/fa7f56d3-c2aa-4dfa-a590-0f59a3653007)
The error continues, I don't know how to solve it

**Comment by 12abz** [comment]
Update manually via zip.

**Comment by RayArmahedgehog** [comment]
same thing

**Comment by 12abz** [comment]
Then use blender 3.#

**Comment by Dragorn421** [comment]
I insist once again, you are not using the latest **revision** of fast64. This has been fixed already.

Note: **revision** is different from **version**. Please follow the instructions in the README to update fast64 to the latest main branch revision.

**Comment by Retro-Hax** [comment]
Hello and yes i am sorry for bringing this up again but i did both what was said so as in Updating via the Updater as well as removing Fast64, restarting Blender v4.0.2 then installing/updating manually Fast64 via the Zip File and then pressing the Button as well.
Same Error:
![Screenshot_2024-03-07_16-03-50](https://github.com/Fast-64/fast64/assets/69952967/f03548f2-3a9a-4bd7-8d84-193bd70825b2)
Now i have not tried it on earlier Version but just incase i may just move downstream to 3.x in the Worstcase as it did destroy my Workflow to some degree

**Comment by jesusyoshi54** [comment]
I tried this on blender 4.0 myself and it worked. The related code to fix this seems to have been done in #296
