### ISSUE TITLE
sm64 expanded rom not working when exporting mario

### ISSUE THREAD

**Issue by NotyCovers** [Fast-64/fast64#307]
when i try to export my custom mario model it gives me this error: 
Size too big: Data ends at 0x122c600, which is larger than the specified range.

and when i put a normal rom with 8 mb it says it's very small but when i expand the rom it dosen't work and it gives me that error

pls help
![marioo](https://github.com/Fast-64/fast64/assets/150549220/d51a8e7a-d95e-462c-a9c9-9b033c304d12)

**Comment by jesusyoshi54** [comment]
Yeah the model doesn't fit in the defined space, this is expected behavior. This prevents overwriting important data and breaking the rom.
change you export location to make this work.
