### ISSUE TITLE
Mario Macro has its behaviour removed???

### ISSUE THREAD

**Issue by Samrtass** [Fast-64/fast64#310]
![image](https://github.com/Fast-64/fast64/assets/84032091/bd21b1d5-4ced-4e8a-8229-3748e819e6b0)

used blender 4.0 and blender 3.6.5 and got the same result.

**Comment by Aeolus1229** [comment]
I have the same issue on 4.0 on a previously successful export
![image](https://github.com/Fast-64/fast64/assets/78156103/98ade301-5828-4a5d-99da-c0524b31f6f3)

**Comment by jesusyoshi54** [comment]
This isn't a fast64 issue this is an issue with the definition of the MARIO macro is bad, something outside fast64s control.
