### ISSUE TITLE
.blend file crashes Blender when opening it.

### ISSUE THREAD

**Issue by MelonSpeedruns** [Fast-64/fast64#311]
Saving a blend file with Fast64 materials and re-opening it just crashes outright a fresh install of Blender 3.3.5 .

After some analysing, the issue seems to come from the Fast3D Library .blend file trying to load at boot.
It works the first time on an empty file, but the second time the loading path gets messed up and Blender crashes.

For example, it tries loading the library .blend file from `C:\Users\Melon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\fast64-main\fast64_internal\f3d\f3d_material_library.blend` even though I installed the plugin locally in a folder on my desktop in my portable Blender install. It's also trying to load from the wrong version of Blender. (4.0 as opposed to 3.3.5)

PS: Modifying the plugin so it doesn't load the Library .blend file allows the file to load properly. But materials will be missing.

**Comment by ExtCan** [comment]
I have the exact same problem, except for me it looks for 3.4's library while I use 4.0. Very bizarre.

**Comment by Dragorn421** [comment]
This is a mistake we'll fix in main

You can use the latest release, it is fine

**Comment by Dragorn421** [comment]
I have no idea why fast64 is looking at the library from a different version though 🤔

**Comment by MelonSpeedruns** [comment]
```py
    dir = ""
    for mod in addon_utils.modules():
        if mod.bl_info.get("name") == "Fast64":
            dir = os.path.join(os.path.dirname(mod.__file__), "fast64_internal", "f3d", "f3d_material_library.blend")
            break
            
    if dir == "":
        return
```

Replacing the beginning of the `link_f3d_material_library` function with this piece of code seems to resolve the wrong path, but it still crashes.

**Comment by Dragorn421** [comment]
Are you using the latest release? (aka https://github.com/Fast-64/fast64/releases/tag/v2.2.0 , not the latest revision)

**Comment by jesusyoshi54** [comment]
Please check if #312 does anything to resolve this

**Comment by Dragorn421** [comment]
I'm not following, you had blender 4.0 crash ???

**Comment by MelonSpeedruns** [comment]
oh yep, any blender version will crash on me if I open a .blend file with fast64 materials

**Comment by Dragorn421** [comment]
I can't reproduce blender 4.0 crashing (I am on Linux Kubuntu 23.10)

as for fast64 loading the `f3d_material_library.blend` from another version I can only assume there is a symlink/hardlink at play sharing the fast64 addon folder between two versions of blender. No idea how you got that set up if you didn't do it manually

**Comment by MelonSpeedruns** [comment]
I'm on a clean windows 11 install here with a clean blener 4.0 and it happens.

**Comment by Dragorn421** [comment]
to be clear can you provide exact steps to reproduce

**Comment by MelonSpeedruns** [comment]
1. Open Blender 4.0
2. set the game to OoT
3. select the cube, go to the Materials tab
4. create a new fast3d material
5. delete the original material
6. save as .blend, close blender
7. double click on the .blend file
8. Blender will crash

**Comment by Dragorn421** [comment]
Thanks

I cannot reproduce this on Linux Kubuntu + Blender 4.0.2 using the slightly altered following steps:

1. `x` Open Blender 4.0.2 in factory settings (`blender --factory-startup`)
1. `x` Go to preferences, enable Fast64 2.2.0
1. set the game to OoT
1. select the cube, go to the Materials tab
1. create a new fast3d material
1. delete the original material
1. save as .blend, close blender
1. `x` Open Blender 4.0.2 in factory settings (`blender --factory-startup`)
1. `x` Go to preferences, enable Fast64 2.2.0
1. `x` open previously saved blend (`Open Recent` > `thefile.blend`)
1. `x` Blender does not crash

**Comment by MelonSpeedruns** [comment]
Found a fix for my issue! Removing ```py
            addon_dir = os.path.dirname(os.path.abspath(__file__))
            new_lib_path = os.path.join(addon_dir, "f3d_material_library.blend")

            if lib_path != new_lib_path:
                logger.info("Reloading the library: %s : %s => %s" % (lib.name, lib_path, new_lib_path))

                lib.filepath = new_lib_path
                lib.reload()```
                
from `f3d_material.py` fixed the crashes completely.

Should I make a PR with that change?

**Comment by MelonSpeedruns** [comment]
Update on this: it seems it was caused by another addon adding a library to the .blend file as well. Disabling that other addon fixed the crashed.
