### ISSUE TITLE
fast64 will not open for some reason due to errors unknown

### ISSUE THREAD

**Issue by boyfriendfnflel** [Fast-64/fast64#319]
when i tried installing fast64, it just, doesn't and shows alot of errors (and i ain't fixin' 'em)
![how](https://github.com/Fast-64/fast64/assets/118694996/56f45495-3718-4780-b54f-cb9e948e2d75)

**Comment by Dragorn421** [comment]
This is an error that typically happens when trying to enable fast64 after it already failed to enable once. It doesn't reflect the actual issue

Restart blender
Open the system console
(Try enabling fast64)
Copypaste all errors from the system console
