### ISSUE TITLE
[BLENDER 4.1] 'NoneType' has no attribute 'draw_layer_1_circle_1' when 'Export Object Geolayout' is clicked

### ISSUE THREAD

**Issue by JArmstrongArt** [Fast-64/fast64#326]
(Discovered in commit [92891ae](https://github.com/Fast-64/fast64/commit/92891ae552f3d0c58a5e4cb9d446be1592ec136d) with 100% replication rate)
![VnHtYjs](https://github.com/Fast-64/fast64/assets/47801313/e0d81b62-abb0-46ae-93cd-e7ad9ae6db53)
I am very inexperienced with the Fast64 add-on, in fact this is my first time using it, but I'm quite sure the errors I'm getting here are not down to my own misuse.
On top of the fact that default Fast3D materials appear solid bright pink in the viewport which also seems suspect, every time I try and 'Export Object Geolayout' on a mesh with an active UV map named UVMap in addition to at least one Fast3D material, I get the error pictured above.
Before I switched my add-on install to commit [92891ae](https://github.com/Fast-64/fast64/commit/92891ae552f3d0c58a5e4cb9d446be1592ec136d), I was getting the error fixed by that commit, so I'm guessing Blender 4.1 support is pretty broken right now given how relatively new Blender 4.1 is?

**Comment by Dragorn421** [comment]
Can you open the system console, then create a new file and redo your steps?
I'd like to know if the system console shows any error at any point and which

<details>

<summary>how to open the "system console"</summary>

![image](https://github.com/Fast-64/fast64/assets/5306619/872422c1-2ea5-4f94-8653-13d28eef3408)

</details>

**Comment by JArmstrongArt** [comment]
Doing only exactly what was neccessary from a fresh .blend file to end up with the screenshot in the first post of this issue's thread, here's the entire system console log:
[https://pastebin.com/yJDFD9G5](https://pastebin.com/yJDFD9G5)

**Comment by Dragorn421** [comment]
the errors show `context.scene.world` being `None`

I can reproduce the material being "shader problem"-pink by removing the scene's world before creating the fast64 material

![image](https://github.com/Fast-64/fast64/assets/5306619/f2117b19-7218-42c2-ac32-e7f9339e20d7)

for the sake of testing, what happens if you redo your thing but create a world after opening a new file

**Comment by JArmstrongArt** [comment]
Well, turns out this is on beginner's inexperience after all :S . Turns out, after adding a World to the Scene as you directed with a copy of the repo from commit [92891ae](https://github.com/Fast-64/fast64/commit/92891ae552f3d0c58a5e4cb9d446be1592ec136d) installed in Blender 4.1, the 'Export Object Geolayout' button works just fine. Sorry for wasting your time!

**Comment by Dragorn421** [comment]
No problem!
You weren't wasting my time, this is something fast64 should probably handle automatically or have a better error at least
Thanks for reporting :)
