### ISSUE TITLE
Broken mat revert displaylists causing vanish cap state to bleed into other displaylists

### ISSUE THREAD

**Issue by AgentXLP** [Fast-64/fast64#331]
When exporting Mario's model, the vanish cap state visibly bleeds into other transparent displaylists. I theorize the whole introduction of F3DEX3 and mat bleeding may have created this bug. This has never occurred until recently and has caused issues for lots of character pack creators on sm64coopdx.
![image](https://github.com/Fast-64/fast64/assets/44549182/ebb41f0e-8c7a-4566-b7d7-88687516b727)
This screenshot was taken on sm64coopdx, a Super Mario 64 PC Port based project.

```c
Gfx mario_Right_Foot_DL_mesh_layer_1_mat_override_metal_0[] = {
	gsSPDisplayList(mat_mario_metal),
	gsSPDisplayList(mario_Right_Foot_DL_mesh_layer_1_tri_0),
	gsSPDisplayList(mat_revert_mario_metal),
	gsDPPipeSync(),
	gsSPSetGeometryMode(G_LIGHTING),
	gsSPClearGeometryMode(G_TEXTURE_GEN),
	gsDPSetCombineLERP(0, 0, 0, SHADE, 0, 0, 0, ENVIRONMENT, 0, 0, 0, SHADE, 0, 0, 0, ENVIRONMENT),
	gsSPTexture(65535, 65535, 0, 0, 0),
	gsDPSetEnvColor(255, 255, 255, 255),
	gsDPSetAlphaCompare(G_AC_NONE),
	gsDPPipeSync(),
	gsSPSetGeometryMode(G_LIGHTING),
	gsSPClearGeometryMode(G_TEXTURE_GEN),
	gsDPSetCombineLERP(0, 0, 0, SHADE, 0, 0, 0, ENVIRONMENT, 0, 0, 0, SHADE, 0, 0, 0, ENVIRONMENT),
	gsSPTexture(65535, 65535, 0, 0, 0),
	gsDPSetEnvColor(255, 255, 255, 255),
	gsDPSetAlphaCompare(G_AC_NONE),
	gsSPEndDisplayList(),
};
```
I'm not exactly an expert at reading and understanding displaylists, but this one for example doesn't look right. It's running the same list of commands twice after the displaylist calls. Using an older version of Fast64 is currently the only real fix for us.

**Comment by Lilaa3** [comment]
Is that not the metal mario override? it seems to be applying the metal material, drawing the foot geometry, reverting metal mario, and then reverting everything (because its the last dl called in the mario model when using metal mario).
Could you send geo.inc.c and model.inc.c

**Comment by Lilaa3** [comment]
@jesusyoshi54

**Comment by amykatname** [comment]
happens when exporting the included mario.blend, here's the files you requested @Lilaa3 
[mario.zip](https://github.com/Fast-64/fast64/files/15180711/mario.zip)

**Comment by amykatname** [comment]
doesn't happen when using [8dd4abd](https://github.com/Fast-64/fast64/commit/8dd4abdaea32db73f87e517c62cad451fdf272ac)

**Comment by Lilaa3** [comment]
Fixed in https://github.com/Fast-64/fast64/commit/1d2e6aee298a4d65e91d18eff94bf8439a896d64
