### ISSUE TITLE
how do i fix this error: 'Mesh' object has no attribute 'calc normal split' 

### ISSUE THREAD

**Issue by superboiiz** [Fast-64/fast64#333]
i was trying to export the mario model but it didnt work, is it because i was using the mario.blend and exporting it into a decompile folder or what?
![mario](https://github.com/Fast-64/fast64/assets/102395484/186a9a3c-660f-4873-88a1-c4bf7fa5820d)

**Comment by superboiiz** [comment]
or is it because im sending it into a file that is not mario decompile

**Comment by Lilaa3** [comment]
Hello! This has been fixed in [this commit](https://github.com/Fast-64/fast64/commit/92891ae552f3d0c58a5e4cb9d446be1592ec136d) please update your fast64 here:
![image](https://github.com/Fast-64/fast64/assets/87947656/b6c4695b-5941-4163-a842-6a147b3dbadc)

**Comment by Lilaa3** [comment]
@superboiiz Just use fast64's update button in the plugins window like i showed
