### ISSUE TITLE
Option to hide SM64/OoT-specific settings

### ISSUE THREAD

**Issue by gubblesdev** [Fast-64/fast64#342]
When developing homebrew outside of modding SM64/OoT (i.e. libdragon), the game-specific fields added by Fast64 in the properties panel present a rather clunky workflow. This is especially noticeable in the object and material tabs, with SM64's Object Geolayout Inspector and Collision Type/Texture Scroll respectively, which are fixed in place and cannot be moved or collapsed. Ideally the user would be able to select a "None" option in place of either game in Fast64's global settings to hide them completely, though even the ability to collapse and reorder the specific panels would help greatly to streamline homebrew workflow.

**Comment by jesusyoshi54** [comment]
Feature added with linked PR
