### ISSUE TITLE
(Blender 4.0.1+) 'Euler' object has no attribute 'to_euler' Error when exporting a Level

### ISSUE THREAD

**Issue by Retro-Hax** [Fast-64/fast64#355]
So as the Title implies i have gotten a very weird issue when it came to exporting my Hubworld to ultrasm64 specifically only this File it seems weirdly enough?
As every other File i export works out of the Box without any Issues i even attempted to copy the LevelRoot and AreaRoot of that broken File and copy them to another File which alos has a Level and there it exports without any Issues so my Question would be what exactly is causing this Bug if it is even a Bug?
![image](https://github.com/Fast-64/fast64/assets/69952967/0248d4ce-5f84-41c0-89d1-9400845f93e6)

![image](https://github.com/Fast-64/fast64/assets/69952967/dbbb5c50-7b66-43ae-8d69-89a87b3f0e5e)

My Level Exporter Settings are Refresh 13, YAY0 and the Export Level is set to Castle Grounds tho honestly even changing the Exported Level did not work :(

**Comment by Romcad82** [comment]
I was just having this issue too, but I was able to export again when I removed the only waterbox from my level. Maybe try removing all waterboxes if you have any and see if that works. For now I just reverted to the previous version of Fast64 and it works fine

**Comment by jesusyoshi54** [comment]
Has been fixed with recent PR

**Comment by s4Ys369** [comment]
this fix needs to be applied to camera volumes as well :]

**Comment by Lilaa3** [comment]
Thank you for catching that
