### ISSUE TITLE
[SM64] Noise texture failing to apply to specific body parts

### ISSUE THREAD

**Issue by SuperKirbylover** [Fast-64/fast64#359]
making custom models for COOPDX for custom characters, and because of the material leak fix, i updated and re-exported all of my models. half of my models exported just fine, but for some reason, certain parts of the rest of the half do not. i'm not sure if this is an issue on my end or it is a fast64 issue, so i'm posting here in hopes that somebody will find out.

what happens is upon the game applying the vanish cap switch, it fails to properly render some body parts with the noise texture. here's some visuals

<img width="193" alt="sm64coopdx_fbJ0dBZAhN" src="https://github.com/Fast-64/fast64/assets/37816816/85647831-702c-44e3-a73f-1923399d8d03">

_the noise's ass is the only body part with the noise material applied._

<img width="225" alt="sm64coopdx_0ZavGOf5xA" src="https://github.com/Fast-64/fast64/assets/37816816/129def07-ec43-4961-bcfd-1f10161a1d2f">

_only gustavo's head and torso are applied correctly._

<img width="213" alt="sm64coopdx_ld5wulLq7F" src="https://github.com/Fast-64/fast64/assets/37816816/3d79e0a8-d890-4a4e-8d40-c5ca0f58ffec">

_only noisette's torso and butt are applied correctly._

**Comment by jesusyoshi54** [comment]
This was caused by an issue with the bones in the armature, not fast64.
