### ISSUE TITLE
Support for other decomps

### ISSUE THREAD

**Issue by nickmux** [Fast-64/fast64#361]
As time goes by more and more decomps have started to make their way to be usable 
If it's possible can you guys please add support for other decomps such as 
https://github.com/sonicdcer/sf64
https://github.com/zeldaret/mm
https://github.com/n64decomp/banjo-kazooie

**Comment by Yanis42** [comment]
easier said than done imo

I wanna try to make MM working though, I was just waiting on the decomp reaching 100% and they were at 94% when I looked few days ago so I'll probably take a look at it soon I guess

**Comment by Reonu** [comment]
> easier said than done imo
> 
> I wanna try to make MM working though, I was just waiting on the decomp reaching 100% and they were at 94% when I looked few days ago so I'll probably take a look at it soon I guess

If you add proper complete MM scene importing I will love you forever
