### ISSUE TITLE
[OoT] Importing a DL with the custom path option doesn't work

### ISSUE THREAD

**Issue by Yanis42** [Fast-64/fast64#384]
I remember we talked about this a while ago on discord and it was brought to my attention again recently. The issue occurs when you try to import something with the DL Exporter with the "Use Custom Path" checkbox enabled (and the corresponding value set)

The error is the following: ``FileNotFoundError: [Errno 2] No such file or directory: '\\\\wsl.localhost\\Ubuntu-22.04\\home\\github\\oot\\assets\\objects\\gameplay_keep\\gameplay_keep.c\\gameplay_keepVtx_00D418.vtx.inc'`` (with ``gBoulderFragmentsDL``), basically it keeps the C file part, I remember looking into this but I couldn't find the reason and I just gave up eventually

**Comment by Dragorn421** [comment]
In a custom export, there is no consideration of being in a decomp repo, you just have a file to read from. When a file does
`#include "assets/scenes/overworld/spot01/spot01_room_0Vtx_001720.vtx.inc"`
, what is fast64 supposed to do?
It doesn't have a decomp repo to look this up in

Currently for some reason fast64 uses the input .c path as that "decomp repo path" which is wrong and leads to the error you have. But I don't trust changing that logic, it may be relied upon elsewhere

**Comment by Dragorn421** [comment]
based on this
https://github.com/Fast-64/fast64/blob/fd2755988309605cd6d1987b413808e33dd0370a/fast64_internal/f3d/f3d_parser.py#L862-L864
it seems like basePath being set as the input .c path is a mistake, the intent was setting the input .c 's folder parent path instead
I'll fix it that way.

Note this doesn't make dlists from maps very importable, for example it misses any texture that may be from the scene file (dlists are typically in room files). For example kakariko imports as fully black
