### ISSUE TITLE
Failure to build with new levels due to missing info: MARIO undeclared.

### ISSUE THREAD

**Issue by GitHubUser-2** [Fast-64/fast64#400]
After exporting my new level to the decomp, I encountered an error where it wouldn't build.  
```
***//mnt/d/sm64-master/sm64-master - Copy (2)$ make
==== Build Options ====
Version:        us
Microcode:      f3d_old
Target:         sm64.us
Compare ROM:    yes
Build Matching: yes
=======================
Building general tools...
Building sm64tools...
Building ROM...
Compiling: levels/bob/script.c -> build/us/levels/bob/script.o
levels/bob/script.c:64:3: error: unterminated argument list invoking macro "MARIO"
   64 | };
      |   ^
levels/bob/script.c:34:9: error: 'MARIO' undeclared here (not in a function)
   34 |         MARIO(MODEL_MARIO, BPARAM4(0x01),
      |         ^~~~~
levels/bob/script.c:65: error: expected '}' at end of input
levels/bob/script.c:28:39: note: to match this '{'
   28 | const LevelScript level_bob_entry[] = {
      |                                       ^
make: *** [Makefile:723: build/us/levels/bob/script.o] Error 1
```
I found out that I could build it after making manual edits. The problem is that Fast64 exports the level script.c with `MARIO(MODEL_MARIO, BPARAM4(0x01),` (which is under `const LevelScript level_bob_entry[]`)  
The `MARIO` line requires an additional `)` at the end (just before the comma). Inside the parentheses, it also needs `bhvMario`.  My manual fix turned the line into `MARIO(MODEL_MARIO, BPARAM4(0x01), bhvMario),`  
Without this change, it fails to build.

**Comment by Yanis42** [comment]
not related to your issue but I noticed this path: ``//mnt/d/sm64-master/sm64-master``, it tells me you're probably using WSL. If that's the case don't use the Windows filesystem (``/mnt/[hard drive letter]``) with WSL as the performances are really bad, use a Linux filesystem instead (any Linux path, like ``/home/username/sm64`` for instance)

also I can see ``sm64-master`` so you probably downloaded the repo as a zip file, it's better to use ``git clone https://github.com/[Username_or_Organization/Repository_Name].git``

**Comment by GitHubUser-2** [comment]
Wow, incredibly fast response! Thanks, I'll try that.

**Comment by Yanis42** [comment]
btw feel free to join the discord server: https://discord.gg/ny7PDcN2x8, you can get more help there (the link is also in the readme)

**Comment by GitHubUser-2** [comment]
Well, I'll try the Discord. Also, still getting the same error even with it natively running WSL filesystem. Even with `clone` instead of .zip

**Comment by Yanis42** [comment]
yeah what I said isn't related to your issue, I'm not able to help for SM64 stuff as I'm an OoT person (hence why I suggested to join the discord)

**Comment by GitHubUser-2** [comment]
\*sigh\* I am using VPN, and can't join. Guess I'll have to disable it.

**Comment by Lilaa3** [comment]
see pr #376, will be merged soon

**Comment by Dragorn421** [comment]
@Lilaa3 this is fixed?

**Comment by Lilaa3** [comment]
> @Lilaa3 this is fixed?
yes
