### ISSUE TITLE
[F3D] Mat bleed issues with tile scrolling

### ISSUE THREAD

**Issue by MrComit** [Fast-64/fast64#412]
In a level model with multiple materials using tile scrolling and multiple materials not using scrolling, exporting with mat bleed caused some mats that shouldnt scroll to scroll, and some mats that should scroll to not

**Comment by Lilaa3** [comment]
Looking at the code this actually seems weird, tile scroll cmds (set tile size command with a tag) will not bleed, and the scroll function is only generated after bleed so it should be using the correct command, do you have a minimal example?
