### ISSUE TITLE
[SM64] Area 2, 3 etc are messed up ingame.

### ISSUE THREAD

**Issue by FrijolesYQueso** [Fast-64/fast64#424]
Using the lastest commits, Areas anything other than 1 are extremely stretched all scales, transforms and the like were applied. Collision is not affected.
![image-1370](https://github.com/user-attachments/assets/5faa1fbd-461d-4910-a64e-ca9cc572c968)

**Comment by Lilaa3** [comment]
broken by https://github.com/Fast-64/fast64/pull/352

**Comment by Dragorn421** [comment]
Partially fixed by #425
No test case to debug any issue left, closing
