### ISSUE TITLE
When i purge mario lowpoly mode it does anything when try to add textures

### ISSUE THREAD

**Issue by SANTIQDCO** [Fast-64/fast64#436]
https://github.com/user-attachments/assets/7cf1f2ad-d055-434d-b70e-9950a2fb2d17

**Comment by Lilaa3** [comment]
It doesn´t even seem like you have fast64 installed
![image](https://github.com/user-attachments/assets/8218404f-97bf-4eb1-bc61-b7e0399ea845)
