### ISSUE TITLE
Unable to view F3D Materials on Fast64 2.2.1 with Blender 4.2.1 LTS

### ISSUE THREAD

**Issue by Retro-Hax** [Fast-64/fast64#439]
So this is a little Hard to describe but basically all my Textures appear black doesnt matter the Color Combiner Preset i use or even if the Texture File Path exists it just does not wanna render i even tried creating a completely new Level from Scratch and even there the Materials just do not seem to get rendered
Also i use the latest Fast64 which as of time of writing this is 2.2.1 and Blender 4.2.1 LTS

Example Geometry
![image](https://github.com/user-attachments/assets/bcac450a-0e26-4c22-94d9-305df998e292)
Fast 64 Settings
![image](https://github.com/user-attachments/assets/d24c7b9f-0e55-4cb5-82b8-fc5eed82630d)
Material Setting for the Geometry Material
![image](https://github.com/user-attachments/assets/1364d61b-c8b3-4341-9c4c-1fe60ff89114)

if more is needed please tell me and i will provide

**Comment by Lilaa3** [comment]
Before opening an issue make sure you're running latest! Fast64 is already on v6
![image](https://github.com/user-attachments/assets/4f031060-4f76-41ea-9c64-2609bcd4e36c)

**Comment by leahanderson1** [comment]
i'm able to replicate this issue in blender 5.0
