### ISSUE TITLE
MSVC 22 'bit' undefined; assuming extern returning in codec_choose.c Line 222		

### ISSUE THREAD

**Issue by micthom** [Fast-64/fast64#444]
I am running into an issue compiling under MSVC. It is related to the HAVE_AVX512 define. I have tried compiling this on i9 and Xeon 8272CL processor.

**Comment by Dragorn421** [comment]
Hi,
You are in the wrong repo

**Comment by micthom** [comment]
What repo would this go to please? This file is included in the git for the project.
