### ISSUE TITLE
OoT/MM scene importing support

### ISSUE THREAD

**Issue by Zelllll** [Fast-64/fast64#5]
- Parse header and create a scene empty with all the same properties
- Support alternate headers on import when creating the empty
- Reuse the code for not duplicating materials that is used in skelanime
- Make sure displaylists are imported on the correct draw layer
- When importing displaylists, disable collision on them
- Create a separate object for collision and disable rendering on it, and just make a different material for each polygon type

**Comment by Dragorn421** [comment]
About importing MM scenes, @kurethedead made a hacky version of fast64 for it

https://discord.com/channels/874816709855440926/874832163483287612/1036182731991826484

> https://github.com/kurethedead/fast64/tree/mm_scene_import_hack
> 1. Clone the mm repo and set the base path in OOT mode for fast64
> 2. Go to OOT Scene Exporter -> Import section -> disable all options except Mesh
> 3. Choose a custom scene, set subfolder to no text, set name to scene folder name in mm/assets/scenes
> 4. For each room file (.c), if there's any #include "misc/scene_texture_...h, copy/paste the .c version of that file to the top of the room file, excluding #include... sections.
> 5. Copy paste all the images in that scene texture folder into the scene folder as well.
> 6. Import 
> 
> This breaks some oot importing features so don't use it for oot scene imports (unless you also only care about meshes) 

Again this is a hack, don't expect support
