### ISSUE TITLE
No access on BitBucket

### ISSUE THREAD

**Issue by HenryIsTheCoder** [Fast-64/fast64#50]
I'm not able to access the original file on BitBucket.

**Comment by thecozies** [comment]
what's the issue? what file?

**Comment by Zelllll** [comment]
It seems that kurethedead took it down. Maybe because of this on GitHub now? I'm not sure, originally it was here: https://bitbucket.org/kurethedead/fast64

**Comment by thecozies** [comment]
ahhh yeah you might be right

**Comment by thecozies** [comment]
@HenryIsTheCoder if there is an actual issue let us know but I'll be closing this tomorrow if i haven't heard back.

**Comment by HenryIsTheCoder** [comment]
okay
