### ISSUE TITLE
Add the option to import materials in order

### ISSUE THREAD

**Issue by AI6490330921902** [Fast-64/fast64#66]
Due to my computer being weak, I can't load the materials tab (or view materials) or it crashes. I would like to be able to have the materials in collision export in order like iProgramInCpp's EasyExporter:
>     // Material.006 Material...
>     COL_TRI_INIT(SURFACE_DEFAULT, 3),
>     COL_TRI(7,3,1),
>     COL_TRI(173,169,167),
>     COL_TRI(189,185,183),
>     // Material.007 Material...
>     COL_TRI_INIT(SURFACE_DEFAULT, 2),
>     COL_TRI(50,54,52),
>     COL_TRI(55,51,49),
>     // Material.008 Material...
>     COL_TRI_INIT(SURFACE_DEFAULT, 4),
>     COL_TRI(48,49,51),
>     COL_TRI(50,51,55),
>     COL_TRI(54,55,53),
>     COL_TRI(52,53,49),
>     // Material.009 Material...

It would be useful for editing manually since I'm kinda used to it at this point, and it'd prevent me from having to rely on other tools or ask others to help with it.

**Comment by AI6490330921902** [comment]
oops meant export in the title of this

**Comment by Dragorn421** [comment]
Closing,
since this is inactive, and also vague, and it seems out of scope for fast64 to compensate for a lack of computer capacity (see https://www.blender.org/download/requirements/ )
