### ISSUE TITLE
Fast64 Enable Issue

### ISSUE THREAD

**Issue by dariodimarcoberardinoRetroHax** [Fast-64/fast64#78]
Hello so i finnaly decided to get the latest Version of Fast64 and while everything work great i am having an issue sadly with Enabling it may be its amn issue on my End as my Blender Version is 3.0.1 and idk if yall support it yet but it kinda is stopping from working on my stuff :(

![image](https://user-images.githubusercontent.com/69952967/154847974-098da6c9-5d86-4f4d-8574-b9e76fcfc381.png)

**Comment by Dragorn421** [comment]
Just to make sure, does the file `fast64_internal/oot/oot_level.py` in your fast64-main folder have `OOT_ObjectProperties` at line 170 like https://github.com/Fast-64/fast64/blob/main/fast64_internal/oot/oot_level.py#L170

@thecozies haven't we seen similar issues before?

**Comment by dariodimarcoberardinoRetroHax** [comment]
Heya :D Sry for the late reply and yes it exists and is there... >.> hmmm.... kinda weird tbh

**Comment by Dragorn421** [comment]
Also just to make sure have you restarted blender after updating fast64

**Comment by dariodimarcoberardinoRetroHax** [comment]
Ooooh :0 no i havent! but that fixed it thanks :3 Goshj i feel kinda stupid now >w<

**Comment by Dragorn421** [comment]
np lol, that should always be the first attempt to solve anything
