### ISSUE TITLE
Fast64 Material Creation Issue

### ISSUE THREAD

**Issue by dariodimarcoberardinoRetroHax** [Fast-64/fast64#83]
![image](https://user-images.githubusercontent.com/69952967/157739881-0203187d-0412-4e99-8773-ae1fc0360bb9.png)

Hello so this happened fairly recently aka an hour ago :P basically i clicked like i normally would on the create F3D Material and all i got was this error tho while i can still use blender the texture is all black :( its a 12x812 texture tho i even large texture mode doesnt make help it :( oh btw im on blender 3.1.0 so that may be the issue >.>

EDIT: im also getting an bpy_prob_collection[index]: index 0 out of range, size 0

which also happens with 32x32 Textures now :(

**Comment by Dragorn421** [comment]
Should now be fixed
