### ISSUE TITLE
Z64 collision normals are calculated incorrectly

### ISSUE THREAD

**Issue by mzxrules** [Fast-64/fast64#88]
In Z64, the components of the normal are stored as a value ranging between -32767 to 32767, representing the value range -1.0 to 1.0. This is NOT the same as the range of values that can possibly stored in a short (-32768 to 32767).
 
Fast64 incorrectly multiplies the normal by 2^15, which is 32768 and clamps it to the range of a short here: 

https://github.com/Fast-64/fast64/blob/58844bafafb07909827e4d153d0fd56851645018/fast64_internal/oot/oot_utility.py#L391

I'm not sure if this is related in any way to the dynapoly bug since normals should be recomputed anyway.

**Comment by Dragorn421** [comment]
I don't think it's an actual issue that normals may be (at most) 1/2^15 off, since that's only doubling the error introduced by rounding

Still, good catch, I'm going to fix this by storing/writing the normals as floats and use `COLPOLY_SNORMAL()` in the polygons data I guess.
